name: Veian's BLOG
markdown: redcarpet
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "config", "sass"]
auto: true
pygments: true
title : Veian's blog
tagline: veian blog
author :
  name : veian
  email : q.787583174@gmail.com
  github : veian

production_url : http://e2024.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
